### ISSUE TITLE
rip only copies bin/ and lib/, breaks packages that depend on files outside of them

### ISSUE THREAD

**Issue by bdimcheff** [defunkt/rip#25]
Since rip only copies bin/ and /lib, any package that uses a file that is not in bin/ or lib/ will break.  For instance, haml doesn't work because it attempts to read a VERSION file in the root of the haml project/gem.

Unfortunately, you can't just copy all the files within the project, because there will undoubtedly be conflicts (VERSION, for instance).  The only solution I can think of off the top of my head is to install the packages in their own folder as rubygems does, and then add a lot more items to RUBYLIB, but this seems less than ideal...

**Comment by defunkt** [comment]
Haml has a VERSION at the root level because they use Jeweler.

I've talked to technicalpickles and future versions of Jeweler will be using lib/package/VERSION. A migration script will be provided.

I think this can be solved on a case by case basis - for instance, it's much easier for Haml to move the VERSION into lib/haml than it is for us to add code to Rip.

On that note, feel free to fork Haml and send them a pull request - I'm sure they'd happily accept it :)

**Comment by bdimcheff** [comment]
I actually don't think that haml uses Jeweler.  They just seem to be using their own VERSION file.  Same idea, though.

Anyhow, I know this is a pretty small change for most libraries, but it might be a bigger problem (as a whole) to get every library out there to conform to the new rule* than it will be to implement something in rip that is compatible with existing libraries.  And I really hope that rip is eventually compatible with everything, because I _really_ want to use it.

\* only put stuff you need at runtime in bin and lib

**Comment by rcrowley** [comment]
For completeness, note that Rails is in this camp, too.  It depends on `fresh_rakefile`, `README`, `configs/`, `doc/`, `environments/`, `helpers/` and `html/` existing next to `bin/` and `lib/`.
