### ISSUE TITLE
Replace symlinking of active environment with configuration file

### ISSUE THREAD

**Issue by luislavena** [defunkt/rip#53]
Hey Guys,

So far, RIP is great, but found that symlink options leaves Windows outside of the equation.

RIP and it's tweaks to RUBYLIB and RUBYOPT can be handled by Windows, but not symlinking for active configuration.

Could you guys consider in the future move from the symlinking way to a plain text file that contains active environment instead?

Thank you.

**Comment by defunkt** [comment]
Can you elaborate on the plaintext file idea? I'd love to explore it but I'm not sure how it would work.

**Comment by jonforums** [comment]
Guessing here, but I suspect Luis may have been thinking along the lines of git's .git/HEAD file or XFCE's .desktop launcher config files.

Could $RIPDIR/active be file containing a "reference" (ala .get/HEAD) to the active environment and used as a source of base path prefix for commands?

**Comment by defunkt** [comment]
I don't really know that much about Windows, but in Unix you can't manipulate a shell's environment variables from a process. So there's no way to change Ruby's load path from a script or program.

This is why we use a symlink: we add the symlink to the load path and never have to worry about changing the load path on the fly (because we can't).

Can you change the load path on the fly reliably on windows?

**Comment by jonforums** [comment]
Just to be sure I understand you, are you talking about the window's shell's %PATH% environment variable rather than Ruby's $LOAD_PATH load path?  So we're not talking about $LOAD_PATH shift and unshift fun, right?  Or maybe it's a combination of both?

If by changing load path on the fly in windows you mean %PATH%, I'm not aware of how do to this dynamically.  I do know you can make progress with creating a "contained" PATH by using SETLOCAL in your .bat script files.

Also, are you aware of NTFS junctions ("windows symlinks")? http://technet.microsoft.com/en-us/sysinternals/bb896768.aspx  Although they appear to be better supported in Vista, I haven't used them enough to know how robust of a solution they'd be.  Would the rip gem need to have a custom DLL/exe for using rip?  CRT compilation issues? etc??  And the usage recommendations in the KB article look interesting.

I don't know what Luis had in mind, but what I wanted to look into was the idea of having $RIPDIR/active reference the base path of the active environment in $RIPDIR and use $LOAD_PATH rewriting trickery so that the 'rip' executable (likely a batch script file in combination with a Ruby script) would get the right working environment when it ran.....'rip' (in C:\Ruby19\bin for example) would likely need some combination of SETLOCAL usage in combination with "ruby.exe -S" invocation.  I hope to make some time to check into this to see if it's anything more than a red herring.

One suggestion, you may want to ping Luis, Roger Pack, or JRuby Charlie on this thread and see what magic they can help stir up :)

**Comment by jonforums** [comment]
In case I don't get to this quickly enough, here's roughly what I'm thinking...maybe someone with some spare time can check into it (or rip it apart and find its flaws) if they're interested.....

This should really be first tested on a Win2K or WinXP box so as to catch any spaces-in-paths issues with having $RIPDIR in places like "C:\Documents and Settings\user"

1) Create a "testrip.bat" file in the primary Ruby bin dir, e.g. "C:\Ruby19\bin"

2) Create a fake $RIPDIR dir structure in "%USERPROFILE%.rip" that contains a couple fake environments each with a "bin" and "lib" dir.  In each "bin" create a simple .bat "command file" that simply calls another .bat in it's corresponding "lib" dir that simply does a unique echo message.

3) Create a "%USERPROFILE%.rip\active" file that simply contains the name (really the relative path to a dir) of the currently active rip environment.

4) Edit the "C:\Ruby19\bin\testrip.bat" to do:

SETLOCAL
set RIPDIR="%USERPROFILE%.rip"

set ARIPENV=[result of parsing "%USERPROFILE%.rip\active" using "FOR /F"]

rem initially create a really restricted PATH, relax as needed based on testing
set PATH=%RIPDIR%\%ARIPENV%\bin;C:\Ruby19\bin;%WINDIR%\system32;%WINDIR%
set RUBYLIB=%RIPDIR%\%ARIPENV%\lib

rem put in some code to handle invocations of "testrip.bat" like
rem       "testrip environment command"
rem in which <command> is the name of the "command file" from step (2)

@CALL <command> and see if the PATH hackery works

5) Test/fix/curse as needed and if all looks good, replace the .bat files in each environment's "bin" and "lib" subdirs with Ruby scripts, update the "testrip.bat" file appropriately, and use "ruby -S <command>" rather than the "@CALL <command>"

6) If things are still holding together start figuring out how to integrate this with RubyGems as RubyGems does a little two step file autogenerating by creating a .bat and a corresponding Ruby script in C:\Ruby19\bin.  Need to hijack/override this?

7) If things are STILL holding, start figuring out what needs to change in the rip source in order to rewrite "%USERPROFILE%.rip\active" in response to a "rip env use" command.

8) STILL holding??...test with JRuby on Win2K/WinXP.

9) STILL holding???...test trying to use both Ruby 1.8 and Ruby 1.9 interpreter on the same system.

10) STILL holding????  Start looking at how to do something similar on my xubuntu system

10) If none of this works, start looking at using dl, ffi to reach down to the Win32 API and investigate if NTFS junction points can safely and reliably emulate symlinking on Win2K+ systems.  Ugh.  Will this break other Ruby implementations such as JRuby, IronRuby, Rubinius????

Three issues I already see with this:
1) limited to single users
2) it assumes that the changing and use of rip environments always uses the "rip" command that runs to completion...no programmatic manipulation.  For example, you probably have to do "rip env use myenv" and let it update "%USERPROFILE.rip\archive" and then run your other commands.
3) running a daemon and being able to correctly use different interpreters an issue???

**Comment by defunkt** [comment]
This sounds pretty great. I guess the question is: what are people on Windows going to use Rip for? Development? Deployment?

I think if we start by targeting those using Rip for development, it'll be easier to tack on deployment (and multi-user support) later on.

**Comment by jonforums** [comment]
I agree; I plan to use Rip first for development.  Play with it, see how it fits in with how I develop, and see what it starts to enable.

I think developers (Windows and non-Windows) will need to first get comfortable with it for development before they try other things.  That's why I think it's _so_ important to make Rip cross-platform early on.  To me, cross-platform minimally means being able to install and run Rip on *nix and Windows XP or higher systems using MRI and JRuby runtimes supporting 1.8.6 and 1.9.x.

Ok, back to this issue....

1) Has any Windows developer yet provided feedback/prototype of this symlinking alternative?  One of us really needs to whip up a prototype branch and git it to you to put into the main repo so others can dig into it.

2) What specific Windows systems do you have access to for testing out ideas, etc?
